"""
Django settings for myshop project.

Generated by 'django-admin startproject' using Django 1.8.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '97vqo*t)m)h_3pjjw4(=9m&kc*-_a*30icly_ifg$80jeg_cbz'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1','fd03c7a2.ngrok.io','savvymavvies.pythonanywhere.com', 'savviemavvies.pythonanywhere.com']


# Application definition

INSTALLED_APPS = (
    'account',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'shop',
    'cart',
    'orders',
    'paypal.standard.ipn',
    'payment',
    'social.apps.django_app.default',


)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',

)

ROOT_URLCONF = 'myshop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'cart.context_processors.cart',




            ],
        },
    },
]

WSGI_APPLICATION = 'myshop.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Chicago'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

CART_SESSION_ID = 'cart'

# django-paypal settings
PAYPAL_RECEIVER_EMAIL = 'esu2017fall2@gmail.com'
PAYPAL_TEST = True



#LOGIN_REDIRECT_URL = '/orders/create'
#LOGIN_URL = 'login'
#LOGOUT_URL = 'logout'
#LOGIN_REDIRECT_URL = 'products'
LOGIN_REDIRECT_URL ='/'
#from django.core.urlresolvers import reverse_lazy

#LOGIN_REDIRECT_URL = reverse_lazy('dashboard')
#LOGIN_URL = reverse_lazy('login')
#LOGOUT_URL = reverse_lazy('logout')
#LOGIN_REDIRECT_URL = reverse_lazy('products')

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'esu2017fall5@gmail.com'
EMAIL_HOST_PASSWORD = 'Volimte2017'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

#AUTHENTICATION_BACKENDS = (
 #   'social.backends.google.GoogleOAuth2',

  #  'django.contrib.auth.backends.ModelBackend',
   # 'account.authentication.EmailAuthBackend',
#)

#SOCIAL_AUTH_FACEBOOK_KEY = '212053486003685'
#SOCIAL_AUTH_FACEBOOK_SECRET = '983893afd8220ec8ae93d5678dd7a133'

#SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '33093874630-3di68rjvhv5eti4l91a0136seuuo6a3p.apps.googleusercontent.com' # Google Consumer Key
#SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = '_ldWZo0TCd2sE-gjW-tDIIMB' # Google Consumer Secret
